name: Application CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  sonar:
    uses: anjaniswarna0/grandcentral-demo/.github/workflows/scan-sonarqube.yml@main

    with:
      project_key: sonarqube-demo-app
      java_version: '21'

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}